kind: pipeline
type: docker
name: build

steps:
- name: build
  image: alpine
  commands:
  - ls -la
  - apk add --no-cache python3 py3-pip
  - version=1.0.3 python setup.py sdist

---

kind: pipeline
type: docker
name: deploy

steps:
- name: build
  image: alpine
  environment:
    TWINE_USERNAME:
      from_secret: TWINE_USERNAME
    TWINE_PASSWORD:
      from_secret: TWINE_PASSWORD
  commands:
  - ls -la
  - pip3 install twine
  - twine upload dist/*