resources:
- name: yamlgen-resource
  type: git
  icon: github
  source:
    uri: https://github.com/razaqK/yamlgen
    branch: master

jobs:
  - name: yamlgen-cicd
    public: true
    plan:
      - get: yamlgen-resource
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: python, tag: 3.7.2 }
          run:
            path: version=1.0.3 python setup.py sdist