resources:
- name: yamlgen-resource
  type: git
  icon: github
  source:
    uri: https://github.com/razaqK/yamlgen
    branch: master

jobs:
  - name: resource-yamlgen-cicd
    public: true
    plan:
      - { get: yamlgen-resource, trigger: true }
      - set_pipeline: yamlgen-cicd
        file: yamlgen-resource/concourse-pipeline.yml