resources:
- name: yamlgen-resource-ci
  type: git
  icon: github
  source:
    uri: https://github.com/razaqK/yamlgen
    branch: master

jobs:
  - name: yamlgencicd-ci
    public: true
    plan:
      - get: yamlgen-resource-ci
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: python, tag: 3.7.2 }
          inputs:
            - name: yamlgen-resource-ci
          outputs:
            - name: artifact
              path: yamlgen-resource-ci/dist
          run:
            path: sh
            args: ["deploy.sh"]
            dir: yamlgen-resource-ci