resources:
- name: yamlgen-resource
  type: git
  icon: github
  source:
    uri: https://github.com/razaqK/yamlgen
    branch: master

jobs:
  - name: yamlgencicd
    public: true
    plan:
      - get: yamlgen-resource
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: python, tag: 3.7.2 }
          inputs:
            - name: yamlgen-resource
          outputs:
            - name: artifact
              path: yamlgen-resource/dist
          run:
            path: yamlgen-resource/deploy.sh
            dir: yamlgen-resource