apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: say-things-in-ci-run
spec:
  pipelineRef:
    name: say-things-in-ci
  resources:
  - name: git-repo
    resourceRef:
      name: git-repo