apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: count-files
spec:
  resources:
      inputs:
        - name: repo
          type: git
          targetPath: code
  steps:
    - name: count
      image: registry.access.redhat.com/ubi8/ubi
      command:
        - /bin/bash
      args: [ '-c', 'echo $(find ./code -type f | wc -l) files in repo' ]

